
spec:
  template:
      spec:
        containers:
        - env:
            - name: GREETING_PREFIX
              value: Hi
            - name: greeter.message
              valueFrom:
                configMapKeyRef:
                  name: spring-app-config
                  key: greeter.message
          